sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t mattiasrunge/mcs .

script:
  - docker run -it mattiasrunge/mcs npm test

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      npm run tag ;
    fi
